version: '3'

services:
  spark-master:
    hostname: spark-master
    build: ./spark-container-build
    ports:
      - "8080:8080" #monitoring nodes and jobs
      - "6066:6066" #REST API
      - "7077:7077" #master node communication port
      - "4040:4040"
      - "18080:18080"
    networks:
      - spark-network
    command:
      /spark/spark-2.2.0-bin-hadoop2.7/bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
  spark-worker1:
    build: ./spark-container-build
    ports:
      - "8081:8081"
      - "6067:6066"
      - "4041:4040"
      - "18081:18080"
    networks:
      - spark-network
    command:
      /spark/spark-2.2.0-bin-hadoop2.7/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
  spark-worker2:
    build: ./spark-container-build
    ports:
      - "8082:8081"
      - "6068:6066"
      - "4042:4040"
      - "4052:4042"
      - "18082:18080"
    networks:
      - spark-network
    command:
      /spark/spark-2.2.0-bin-hadoop2.7/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
#  spark-submit:
#    build: ./spark-container-build
#    ports:
#      - "8082:8080"
#      - "6068:6066"
#      - "4042:4040" #monitoring port
#    networks:
#      - spark-network
#    command:
#      /usr/local/share/spark/spark-2.2.0-bin-hadoop2.7/bin/spark-submit --class com.geekcap.javaworld.sparkexample.WordCount --master spark://spark-master:7077 /usr/local/share/spark/spark-2.2.0-bin-hadoop2.7/spark-app/spark-wordcount-1.0-SNAPSHOT.jar
networks:
  spark-network:
