version: '3'

services:
  spark-master:
    hostname: spark-master
    build: ./spark-master-container-build
    ports:
      - "8080:8080"
      - "6066:6066"
      - "7077:7077"
    networks:
      - spark-network
  spark-slave:
    build: ./spark-slave-container-build
    ports:
      - "8081:8080"
      - "6067:6066"
    networks:
      - spark-network
  spark-submit:
    build: ./spark-slave-container-build
    ports:
      - "8082:8080"
      - "6068:6066"
    networks:
      - spark-network
networks:
  spark-network:
