version: '3'

services:
  hadoop-namenode:
    build: ./hadoop-container-build
    ports:
      - "8080:8080"
    networks:
      - hadoop-network
  
#  hadoop-slave:
#    build: ./hadoop-container-build
#    ports:
#      - "8081:8080"
#    networks:
#      - hadoop-network

networks:
  hadoop-network:
